---
- name: run ansible galaxy
	hosts: localhost
	tasks:
	- command: ansible-galaxy install -r ./roles/requirements.yml --force
		delegate_to : localhost
  - command: ansible-galaxy collection install -r roles/requirements.yml --force
    delegate_to : localhost

- name: Install K8S Master nodes
  hosts: k8s-masters
  tasks:
  - name: Prepare nodes for Kubeadm
    include_role:
      name: prepare-k8s-node
  