---
- name: Install K8S Master nodes
  hosts: k8s-masters
  tasks:
  - name: Download dependencies
    local_action:
      command ansible-galaxy install -r requirements.yaml  --roles-path roles --force
  
  - name: Prepare nodes for Kubeadm
    include_role:
      name: prepare-k8s-node
  