---
- name: Install K8S Master nodes
  hosts: k8s-masters
  tasks:
  - name: Prepare nodes for Kubeadm
    include_role:
      name: prepare-k8s-node
  - name: Install Kubernetes master nodes
    include_role:
      name: install-k8s-master